### ISSUE TITLE
Native ads crash on release version (only on  HUAWEI P30 Android 10 (SDK 29))

### ISSUE THREAD

**Issue by nithinfrancis** [googlecodelabs/admob-inline-ads-in-flutter#14]
Native ads crashed on  huawei P30,its work perfectly on almost any other devices

`java.lang.NullPointerException: 	at com.sample.sample.ListTileNativeAdFactory.createNativeAd(ListTileNativeAdFactory.java:143)
	at io.flutter.plugins.googlemobileads.FlutterNativeAd$2.onUnifiedNativeAdLoaded(Unknown Source:12)
	at com.google.android.gms.internal.ads.zzahh.zza(zzahh.java:7)
	at com.google.android.gms.internal.ads.zzagj.zza(zzagj.java:31)
	at com.google.android.gms.internal.ads.zzgy.onTransact(zzgy.java:22)
	at android.os.Binder.transact(Binder.java:921)
	at gc.bb(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:2)
	at com.google.android.gms.ads.internal.formats.client.ak.e(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
	at com.google.android.gms.ads.nonagon.ad.nativead.ad.run(Unknown Source:5)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at qy.a(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
	at com.google.android.gms.ads.internal.util.zzae.setAppMuted(zzae.java:1)
	at qy.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@210890500@210890500057.359169010.359169010:0)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8387)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)`

**Comment by kunny** [comment]
I recently updated the sample code - so please check that out whether it solves the issue or not. :)
