### ISSUE TITLE
Flutter Web has issues!

### ISSUE THREAD

**Issue by Puspharaj** [googlecodelabs/admob-inline-ads-in-flutter#24]
There is no mention of google ads in flutter web, though its under review. This plugin cause flutter web to crash. 

Says this. 

`Error: MissingPluginException(No implementation found for method MobileAds#updateRequestConfiguration on channel plugins.flutter.io/google_mobile_ads)
    at Object.throw_ [as throw] (http://localhost:50001/dart_sdk.js:5041:11)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:50001/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:50001/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:50001/dart_sdk.js:37274:59)
`

**Comment by kunny** [comment]
Google Mobile Ads plugin does not support web platform. So that's an intended behavior.
