### ISSUE TITLE
crashes on android 4.4 (API 19)

### ISSUE THREAD

**Issue by sultanmyrza** [googlecodelabs/admob-inline-ads-in-flutter#9]
I downloaded complete_kotlin_swift and tried to run on `android emulator android 4.4 (API 19)`

```
Launching lib/main.dart on Google Nexus 5 in debug mode...
Running Gradle task 'assembleDebug'...
I/flutter ( 1669): Ad load failed (code=0 message=Internal error.)
E/flutter ( 1669): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.IllegalStateException: maxImages (3) has already been acquired, call #close before acquiring more.
E/flutter ( 1669): 	at android.media.ImageReader.acquireNextImage(ImageReader.java:346)
E/flutter ( 1669): 	at android.media.ImageReader.acquireLatestImage(ImageReader.java:242)
E/flutter ( 1669): 	at io.flutter.embedding.android.FlutterImageView.acquireLatestImage(FlutterImageView.java:203)
E/flutter ( 1669): 	at io.flutter.embedding.android.FlutterView.acquireLatestImageViewFrame(FlutterView.java:1089)
E/flutter ( 1669): 	at io.flutter.plugin.platform.PlatformViewsController.onEndFrame(PlatformViewsController.java:810)
E/flutter ( 1669): 	at io.flutter.embedding.engine.FlutterJNI.onEndFrame(FlutterJNI.java:982)
E/flutter ( 1669): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 1669): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter ( 1669): 	at android.os.Looper.loop(Looper.java:123)
E/flutter ( 1669): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/flutter ( 1669): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter ( 1669): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter ( 1669): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/flutter ( 1669): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/flutter ( 1669): 	at dalvik.system.NativeStart.main(Native Method)
E/flutter ( 1669): 
F/flutter ( 1669): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1440)] Check failed: CheckException(env). 
E/flutter ( 1964): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.IllegalStateException: maxImages (3) has already been acquired, call #close before acquiring more.
E/flutter ( 1964): 	at android.media.ImageReader.acquireNextImage(ImageReader.java:346)
E/flutter ( 1964): 	at android.media.ImageReader.acquireLatestImage(ImageReader.java:242)
E/flutter ( 1964): 	at io.flutter.embedding.android.FlutterImageView.acquireLatestImage(FlutterImageView.java:203)
E/flutter ( 1964): 	at io.flutter.embedding.android.FlutterView.acquireLatestImageViewFrame(FlutterView.java:1089)
E/flutter ( 1964): 	at io.flutter.plugin.platform.PlatformViewsController.onEndFrame(PlatformViewsController.java:810)
E/flutter ( 1964): 	at io.flutter.embedding.engine.FlutterJNI.onEndFrame(FlutterJNI.java:982)
E/flutter ( 1964): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 1964): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter ( 1964): 	at android.os.Looper.loop(Looper.java:123)
E/flutter ( 1964): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/flutter ( 1964): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter ( 1964): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter ( 1964): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/flutter ( 1964): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/flutter ( 1964): 	at dalvik.system.NativeStart.main(Native Method)
E/flutter ( 1964): 
F/flutter ( 1964): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1440)] Check failed: CheckException(env). 
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:62128/Bl66Kpo3oYI=/
```

## My Setup
```
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 2.0.4 at /Users/******/flutter
    • Framework revision b1395592de (3 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

```
## pubspec.yaml
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # COMPLETE: Add google_mobile_ads as a dependency
  google_mobile_ads: ^0.12.1+1
  flutter_gallery_assets: ^1.0.2
```

**Comment by kunny** [comment]
It looks like there is an existing bug entry: https://github.com/flutter/flutter/issues/63897

Could you post your case on the above issue thread?
